export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAILURE = 'ITEMS_FAILURE';
export const ITEMS_TIMEOUT = 'ITEMS_TIMEOUT';
export const ITEMS_SELECT  = 'ITEMS_SELECT';
export const ITEMS_PURCHASING  = 'ITEMS_PURCHASING';
export const ITEMS_PURCHASED  = 'ITEMS_PURCHASED';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_TIMEOUT = 'USER_TIMEOUT';

export const ANNOUNCEMENT_LOADING = 'ANNOUNCEMENT_LOADING';
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS';
export const ANNOUNCEMENT_FAILURE = 'ANNOUNCEMENT_FAILURE';
export const ANNOUNCEMENT_TIMEOUT = 'ANNOUNCEMENT_TIMEOUT';

export const BOUNTY_LOADING = 'BOUNTY_LOADING';
export const BOUNTY_SUCCESS = 'BOUNTY_SUCCESS';
export const BOUNTY_FAILURE = 'BOUNTY_FAILURE';
export const BOUNTY_TIMEOUT = 'BOUNTY_TIMEOUT';
export const BOUNTY_SELECT  = 'BOUNTY_SELECT';
export const BOUNTY_APPLIED  = 'BOUNTY_APPLIED';
export const BOUNTY_APPLYING  = 'BOUNTY_APPLYING';

