export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAILURE = 'ITEMS_FAILURE';
export const ITEMS_TIMEOUT = 'ITEMS_TIMEOUT';

export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_TIMEOUT = 'USER_TIMEOUT';

export const ANNOUNCEMENT_LOADING = 'ANNOUNCEMENT_LOADING';
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS';
export const ANNOUNCEMENT_FAILURE = 'ANNOUNCEMENT_FAILURE';
export const ANNOUNCEMENT_TIMEOUT = 'ANNOUNCEMENT_TIMEOUT';
