export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAILURE = 'ITEMS_FAILURE';
export const ITEMS_TIMEOUT = 'ITEMS_TIMEOUT';

export const CURRENT_USER_LOADING = 'CURRENT_USER_LOADING';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE';
export const CURRENT_USER_TIMEOUT = 'CURRENT_USER_TIMEOUT';
